### ISSUE TITLE
Use variable as argument of a function

### ISSUE THREAD

**Issue by chikamichi** [tbranyen/combyne#61]
Hi,

I wonder whether it is possible to use a variable as an argument of a function (Property).

My use-case is pluralization of i18n strings. Starting with the following:

``` coffeescript
i18nFn =
   i18n: (key, options) =>
      # options could either be an object, or a integer in which case it's a count.
      # Here, I'm interested by the use-case with a count argument.
      @langManager.engine.t(key, options)
```

then passing `i18nFn` to a rendering context allows me to write things like

```
{{i18n 'some.translation.key'}}
```

But, when it comes to pluralization, I would need to be able to write things like

```
{{i18n 'some.translation.key' count}}
```

where `count` is part of the rendering context (`data`) and should evaluate to an integer, say `3`. Unfortunately, this raises a ReferenceError (count is not defined).

How could one work around this?

The compiled template would currently look like:

```
[…] encode(data['i18n']('some.translation.key',count)) […]
```

which is short a `data[]` accessor/context on the `count` variable to make it right! Would you think poking for the data object as a possible fallback value for otherwise undefined argument would do the trick? `(count || data["count"])` that is, or maybe using `.call` to enforce the scope to `data`? It would not support any variable to fit in, just those in the scope of the current context, which seems to be ok.

Thank you.

**Comment by chikamichi** [comment]
@tbranyen hi, I wonder whether it would be possible to add the same kind of support to %if conditionals?

So that one could write things like `{%if modifiedAmount == amount %}…{%else%}…{%endif%}`, with both `amount` and `modifiedAmount` properties of the rendering context.

**Comment by tbranyen** [comment]
Hrm, that should be trivial now, I'll try and get that feature in tomorrow

**Comment by chikamichi** [comment]
@tbranyen hi, just lurking around wondering whether you hacked something :) :cookie:
