### ISSUE TITLE
how to use "<" and ">" character in generated code

### ISSUE THREAD

**Issue by JerryYangJin** [tbranyen/combyne#86]
Hello, I have "<" and ">" in the json file, in the generated code, it's converted to `&lt;` and `&gt;`

How do i use "<" and ">" in generated code?

Thanks!

**Comment by tbranyen** [comment]
https://github.com/tbranyen/combyne/blob/master/README.md#security

**Comment by tbranyen** [comment]
Specially:

> By default all templates are encoded to avoid possible issues arising from XSS attacks. This is specifically applied to properties and you can avoid this by using the raw property style: {{{ value }}}. This is very similar to Mustache.

Let me know if you're still stuck!
