### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

### ISSUE THREAD

**Issue by quantjin** [tbranyen/combyne#87]
Hello,

I'm using `~0.8.1`, and following the same process of [nodegit](https://github.com/nodegit/nodegit) project, when I generate source code from template, i got below error message

Please advise, thanks!

``` sh
<--- Last few GCs --->

   39211 ms: Scavenge 700.3 (737.9) -> 700.3 (737.9) MB, 12.0 / 0 ms (+ 16.0 ms
in 1 steps since last GC) [allocation failure] [incremental marking delaying mar
k-sweep].
   40209 ms: Mark-sweep 700.3 (737.9) -> 696.2 (737.9) MB, 985.6 / 0 ms (+ 16.0
ms in 2 steps since start of marking, biggest step 16.0 ms) [last resort gc].
   41195 ms: Mark-sweep 696.2 (737.9) -> 696.1 (737.9) MB, 989.1 / 0 ms [last re
sort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 17B6CC95 <JS Object>
    1: constructProperty [\node_modules\combyne\dist\c
ombyne.js:~634] [pc=083DF926] (this=10B1D319 <a Tree with map 21B4FD51>,encoded=
17B08115 <true>)
    2: constructConditional [\node_modules\combyne\dis
t\combyne.js:905] [pc=0839A922] (this=10B1D319 <a Tree with map 21B4FD51>,root=1
0B1D33D <an Object with map 21B4FEB1>,kind=09249239 <String[8]: ST...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
```

**Comment by tbranyen** [comment]
Have you tried upgrading to 2.0?

**Comment by JerryYangJin** [comment]
@tbranyen , thanks for the update, please ignore this, it turns out there's something wrong in the partials, it didn't throw any error, and got stuck at `templates.class_content.registerPartial(partial, combyne(partials[partial]));` step
after correcting the error in partial, everything is working fine again

**Comment by tbranyen** [comment]
Awesome, glad you got it working!

**Comment by kadamwhite** [comment]
Gentle suggestion that this issue be repurposed or a new one be opened to address the swallowed error, that sounds like a bug?
